/**
 * Shared domain types for the DEUS VULT simulation.
 *
 * Design notes that are load-bearing elsewhere:
 *
 *  - A counter is a *platoon*: 3-4 vehicles or ~30 soldiers. Strength is
 *    measured in 10 abstract steps so damage reads legibly on a phone
 *    ("STR 7/10") without exposing per-man bookkeeping.
 *
 *  - Sensing and shooting are deliberately separate capabilities. A unit's
 *    ability to *find* something is described by `sensors`; its ability to
 *    *hurt* it by `weapons`. Long-range weapons require a quality of contact
 *    that most shooters cannot generate for themselves. This split is the
 *    game's signature system.
 *
 *  - Everything here is plain data and structurally serializable. GameState
 *    survives JSON.stringify/parse unchanged, which is what makes saves,
 *    replays and headless balance runs cheap.
 */

import type { Hex } from './hex';

/* ------------------------------------------------------------------ */
/* Sides and nations                                                   */
/* ------------------------------------------------------------------ */

export type Side = 'BLUE' | 'RED';

export const SIDES: readonly Side[] = ['BLUE', 'RED'];

export function opposingSide(side: Side): Side {
  return side === 'BLUE' ? 'RED' : 'BLUE';
}

/**
 * Real militaries in a fictional flashpoint. Nations are characterised by
 * doctrine — how they fight — never by anything else. See docs/GDD.md
 * §Fiction for the editorial standard this content is held to.
 */
export type Nation = 'USA' | 'JPN' | 'AUS' | 'CHN';

export interface NationProfile {
  readonly id: Nation;
  readonly name: string;
  readonly shortName: string;
  readonly side: Side;
  /** One-line doctrinal thesis, surfaced in the codex. */
  readonly doctrine: string;
}

/* ------------------------------------------------------------------ */
/* Domains, classes, armour                                            */
/* ------------------------------------------------------------------ */

export type Domain = 'LAND' | 'AIR' | 'SEA';

export type UnitClass =
  | 'INFANTRY'
  | 'RECON'
  | 'ARMOR'
  | 'IFV'
  | 'ARTILLERY'
  | 'MRL'
  | 'SAM'
  | 'UAV'
  | 'EW'
  | 'ASM'
  | 'ENGINEER'
  | 'TRANSPORT'
  | 'HELO'
  | 'SHIP';

/**
 * Target profile for lethality lookup. Kept coarse on purpose: five classes
 * produce a counter matrix a player can actually hold in their head, which is
 * the whole point of combined arms.
 */
export type ArmorClass = 'SOFT' | 'LIGHT' | 'HEAVY' | 'AIR' | 'NAVAL';

/* ------------------------------------------------------------------ */
/* Sensing                                                             */
/* ------------------------------------------------------------------ */

/**
 * Sensor modalities. The interesting asymmetry is that RADAR is *active* —
 * using it lights you up for every ELINT receiver in the theatre, typically
 * at greater range than the radar itself can see. That single trade is the
 * source of most of the game's tension.
 */
export type SensorType = 'OPTICAL' | 'THERMAL' | 'RADAR' | 'ELINT' | 'ACOUSTIC';

export interface Sensor {
  readonly type: SensorType;
  /** Detection range in hexes. */
  readonly range: number;
  /**
   * Base detection power. Compared against a target's signature in the
   * matching spectrum; see sensors.ts for the exact contest.
   */
  readonly power: number;
  /** True if operating this sensor emits and can itself be detected. */
  readonly active: boolean;
  /** Whether terrain and elevation block this modality. */
  readonly needsLineOfSight: boolean;
  /** Domains this sensor can detect at all. */
  readonly detects: readonly Domain[];
}

/**
 * How loud a unit is in each spectrum, before situational modifiers.
 * Scale is roughly 0 (undetectable) to 100 (a radar at full power).
 */
export interface Signature {
  readonly visual: number;
  readonly thermal: number;
  /** Radar cross-section — how well it reflects someone else's radar. */
  readonly radar: number;
  /** Active RF emissions — how loud it is to a passive listener. */
  readonly rf: number;
  readonly acoustic: number;
}

/**
 * Quality of contact. This is the core resource of the game.
 *
 *  UNDETECTED — not on the map at all for this side.
 *  CONTACT    — something is there. Position known, identity not. Cannot be
 *               engaged by precision fires; area fire only.
 *  IDENTIFIED — type known. Direct-fire weapons may engage.
 *  TRACKED    — fire-control quality. Required for indirect and missile
 *               fires. Usually generated by a *different* unit than the one
 *               shooting, which is the sensor-shooter link.
 */
export enum DetectionLevel {
  UNDETECTED = 0,
  CONTACT = 1,
  IDENTIFIED = 2,
  TRACKED = 3,
}

export const DETECTION_LABELS: Readonly<Record<DetectionLevel, string>> = {
  [DetectionLevel.UNDETECTED]: 'No contact',
  [DetectionLevel.CONTACT]: 'Contact',
  [DetectionLevel.IDENTIFIED]: 'Identified',
  [DetectionLevel.TRACKED]: 'Tracked',
};

/** What one side currently believes about one enemy unit. */
export interface Contact {
  readonly unitId: UnitId;
  level: DetectionLevel;
  /** Where the contact was last observed — may be stale. */
  lastSeen: Hex;
  /** Turn number of the last observation. */
  lastSeenTurn: number;
  /** Sensor modalities currently holding this contact. */
  by: SensorType[];
  /**
   * True when the contact is a memory rather than a live observation. Stale
   * contacts are drawn ghosted and cannot be engaged by precision fires.
   */
  stale: boolean;
}

/* ------------------------------------------------------------------ */
/* Weapons                                                             */
/* ------------------------------------------------------------------ */

export type FireMode =
  /** Shooter must see the target itself. */
  | 'DIRECT'
  /** Fired on someone else's track; shooter needs no line of sight. */
  | 'INDIRECT'
  /** Long-range precision; requires TRACKED and consumes scarce ammunition. */
  | 'MISSILE';

export interface Weapon {
  readonly id: string;
  readonly name: string;
  readonly mode: FireMode;
  /** Minimum engagement range in hexes; 0 for most direct-fire weapons. */
  readonly rangeMin: number;
  readonly rangeMax: number;
  /**
   * Rounds of effective fire in one attack. This is the `n` of the binomial —
   * a larger volley means a tighter, more predictable damage distribution.
   */
  readonly volley: number;
  /** Base single-round hit probability at optimal range, before modifiers. */
  readonly accuracy: number;
  /** Strength steps removed per hit, before the lethality matrix. */
  readonly damage: number;
  /** Multiplier applied per target armour class. */
  readonly lethality: Readonly<Record<ArmorClass, number>>;
  /** Domains this weapon can engage. */
  readonly engages: readonly Domain[];
  /** Contact quality required to open fire. */
  readonly requires: DetectionLevel;
  /** Suppression inflicted per round of fire, hit or miss. */
  readonly suppression: number;
  /** Limited munitions; undefined means effectively unlimited. */
  readonly ammo?: number;
  /** Firing reveals the shooter this much, added to RF/visual signature. */
  readonly firingSignature: number;
}

/* ------------------------------------------------------------------ */
/* Units                                                               */
/* ------------------------------------------------------------------ */

export type UnitDefId = string;
export type UnitId = string;

/** Static template. Content data, never mutated at runtime. */
export interface UnitDef {
  readonly id: UnitDefId;
  readonly name: string;
  /** Real-world designation, e.g. "M1A2 SEPv3". Display only. */
  readonly designation: string;
  readonly nation: Nation;
  readonly unitClass: UnitClass;
  readonly domain: Domain;
  readonly armor: ArmorClass;
  readonly maxStrength: number;
  /** Movement points per turn. */
  readonly movement: number;
  /** Terrain cost profile; see terrain.ts. */
  readonly mobility: MobilityType;
  readonly sensors: readonly Sensor[];
  readonly signature: Signature;
  readonly weapons: readonly Weapon[];
  /** Hexes of elevation-independent spotting bonus for elevated platforms. */
  readonly altitude: number;
  /** Resistance to suppression, 0..1. Veterans and heavy armour shrug it off. */
  readonly discipline: number;
  readonly abilities: readonly AbilityId[];
  /** Requisition cost in the campaign layer. */
  readonly cost: number;
  /** Codex text. */
  readonly description: string;
}

export type MobilityType = 'FOOT' | 'WHEELED' | 'TRACKED' | 'AIR' | 'NAVAL' | 'AMPHIBIOUS';

export type AbilityId =
  | 'EMCON'
  | 'RADAR_ON'
  | 'JAM'
  | 'DECOY'
  | 'OVERWATCH'
  | 'HUNKER'
  | 'DESIGNATE'
  | 'FORTIFY'
  | 'RESUPPLY';

/** Runtime instance. Mutable, serializable, owned by GameState. */
export interface Unit {
  readonly id: UnitId;
  readonly defId: UnitDefId;
  readonly side: Side;
  /** Persistent callsign; survives across the campaign. */
  callsign: string;
  pos: Hex;
  strength: number;
  /** 0..100. Degrades accuracy and movement; see combat.ts. */
  suppression: number;
  movementLeft: number;
  /** False once the unit has taken its action for the turn. */
  hasActed: boolean;
  /** Radar and other active sensors are off unless switched on. */
  emitting: boolean;
  /** Overwatch: fires on the first enemy to move within range. */
  onOverwatch: boolean;
  /** Hunkered units are harder to hit and harder to see, but cannot act. */
  hunkered: boolean;
  fortified: boolean;
  /** Remaining rounds per weapon id. */
  ammo: Record<string, number>;
  /**
   * Recent-activity signature boost. Moving, firing and switching on a radar
   * all raise it; it halves at the start of each of the owner's turns. This
   * is what makes "shoot and scoot" a real behaviour rather than a slogan —
   * a battery that just fired is loud for a turn afterwards.
   */
  disturbance: number;
  /** Campaign veterancy, 0..5. Applies accuracy and discipline bonuses. */
  veterancy: number;
  /** Missions survived; drives veterancy gain. */
  experience: number;
  /** Set when destroyed; the unit is retained for after-action reporting. */
  destroyed: boolean;
  /** Turn on which the unit was destroyed, for the replay timeline. */
  destroyedTurn?: number;
}

/* ------------------------------------------------------------------ */
/* Map                                                                 */
/* ------------------------------------------------------------------ */

export type TerrainId =
  | 'OCEAN'
  | 'SHALLOWS'
  | 'BEACH'
  | 'PLAIN'
  | 'FIELD'
  | 'SCRUB'
  | 'FOREST'
  | 'JUNGLE'
  | 'HILL'
  | 'RIDGE'
  | 'MOUNTAIN'
  | 'URBAN'
  | 'AIRFIELD'
  | 'PORT'
  | 'ROAD';

export interface TerrainDef {
  readonly id: TerrainId;
  readonly name: string;
  /** Movement point cost by mobility type; Infinity means impassable. */
  readonly cost: Readonly<Record<MobilityType, number>>;
  /** Elevation in levels; affects line of sight. */
  readonly elevation: number;
  /** How much this tile blocks line of sight through it. */
  readonly losBlock: number;
  /** Reduction to incoming hit probability, 0..1. */
  readonly cover: number;
  /** Reduction to the occupant's visual and thermal signature, 0..1. */
  readonly concealment: number;
  /** Display colour, tactical palette. */
  readonly color: number;
}

export interface MapTile {
  readonly hex: Hex;
  terrain: TerrainId;
  /** Objective marker id, if this tile is an objective. */
  objective?: string;
}

export interface GameMap {
  readonly width: number;
  readonly height: number;
  /** Keyed by hexKey. */
  readonly tiles: Map<number, MapTile>;
}

/* ------------------------------------------------------------------ */
/* Objectives and victory                                              */
/* ------------------------------------------------------------------ */

export type ObjectiveKind =
  | 'CAPTURE'
  | 'DESTROY'
  | 'SURVIVE'
  | 'ESCORT'
  | 'DENY'
  | 'RECON';

export interface Objective {
  readonly id: string;
  readonly kind: ObjectiveKind;
  readonly label: string;
  readonly side: Side;
  /** Hexes involved, for CAPTURE / DENY / RECON. */
  readonly hexes?: readonly Hex[];
  /** Unit ids involved, for DESTROY / ESCORT. */
  readonly unitIds?: readonly UnitId[];
  /**
   * Unit *types* involved, for DESTROY. Preferred over unitIds in authored
   * missions: runtime ids depend on deployment order, so referencing them
   * from content silently breaks the moment a designer reorders the order of
   * battle. "Destroy the landing force" is also what the brief actually says.
   */
  readonly defIds?: readonly UnitDefId[];
  /** Turn deadline, for SURVIVE and timed captures. */
  readonly byTurn?: number;
  /** Optional objectives contribute to score but not to victory. */
  readonly optional: boolean;
  complete: boolean;
  failed: boolean;
}

export type MissionOutcome = 'ONGOING' | 'VICTORY' | 'DEFEAT' | 'DRAW';

/* ------------------------------------------------------------------ */
/* Game state                                                          */
/* ------------------------------------------------------------------ */

export type Phase = 'DEPLOYMENT' | 'BATTLE' | 'RESOLVED';

export interface GameState {
  readonly missionId: string;
  readonly seed: string;
  turn: number;
  maxTurns: number;
  activeSide: Side;
  phase: Phase;
  outcome: MissionOutcome;
  map: GameMap;
  units: Map<UnitId, Unit>;
  /** Per-side belief about enemy units, keyed by observer side. */
  contacts: Record<Side, Map<UnitId, Contact>>;
  /**
   * Laser/data-link designations: enemy unit id -> turn on which the
   * designation lapses. A designated target counts as TRACKED for every
   * shooter on that side, which is the explicit sensor-shooter handoff.
   */
  designations: Record<Side, Map<UnitId, number>>;
  /** Active jamming footprints, recomputed each turn. */
  jamming: Map<number, number>;
  /** Decoys currently deployed, presented to the enemy as false contacts. */
  decoys: Decoy[];
  objectives: Objective[];
  /** Monotonic counter for id generation; keeps ids replay-stable. */
  nextEntityId: number;
  /** Append-only log of everything that happened, for replay and AAR. */
  log: LogEntry[];
  rngState: import('./rng').RngState;
}

/**
 * A deployed decoy.
 *
 * Decoys are spawned as ordinary units with an inflated signature, no
 * weapons and a single strength step. Modelling them this way rather than as
 * a parallel entity type means every existing system — detection, targeting,
 * AI threat assessment — handles them correctly for free, and the enemy can
 * genuinely be induced to spend a missile on one.
 */
export interface Decoy {
  readonly unitId: UnitId;
  /** Turns remaining before the emitter runs down. */
  ttl: number;
}

export type LogSeverity = 'INFO' | 'CONTACT' | 'COMBAT' | 'LOSS' | 'OBJECTIVE';

export interface LogEntry {
  readonly turn: number;
  readonly side: Side;
  readonly severity: LogSeverity;
  readonly message: string;
  /** Hex the entry refers to, so the UI can focus the camera on it. */
  readonly at?: Hex;
}
